/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

import { Html } from 'drei'
import { useSpring } from '@react-spring/core'
import { a } from '@react-spring/three'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Label.glb')

  const [expand, setExpand] = useState(false);
  // React spring expand animation

  const animatedProps = useSpring({
    hovered: expand ? [0.4, 0.4, 0.4] : [0.3, 0.3, 0.3],
  });

  return (
    <a.group 
      ref={group} 
      {...props} 
      dispose={null}
      rotation={[Math.PI / -0.9, 1, 0.4]}
      position={[-4, -0.5, 2]}
      scale={animatedProps.hovered}
      onPointerOver={() => setExpand(true)}
      onPointerOut={() => setExpand(false)}
      // rotation={[1.67, 0.2, 0.7]}
      >
      <group >
        <group position={[0, 0, -0.29]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[1.39, -0.05, 0.37]}>
              <mesh material={materials.Lable_V3} geometry={nodes.Lable_V3_Lable_02_001.geometry} />
            </group>
            <group position={[-1.38, -0.02, 1.49]}>
              <mesh material={materials.Lable_V3} geometry={nodes.Lable_V3_Lable_01_001.geometry} />
            </group>
            <group position={[0.55, 0, -4.29]}>
              <mesh material={materials.Lable_V3} geometry={nodes.Lable_V3_Rope_001.geometry} />
            </group>
            <group position={[1.39, 0.02, -3.04]}>
              <mesh material={materials.Metal} geometry={nodes.Lable_V3_Metal_01_001.geometry} />
            </group>
            <group position={[1.39, 0.02, -3.13]}>
              <mesh material={materials.Lable_V3} geometry={nodes.Lable_V3_Metal_02_001.geometry} />
            </group>
          </group>
        </group>
      </group>
      <Html scaleFactor={5} position={[-0.1, 5.5, 0.3]}>
        <h1 style={{ color: 'white', opacity: '0.1' }}>Brand</h1>
      </Html>
    </a.group>
  )
}

useGLTF.preload('/Label.glb')
