/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

import { Html } from 'drei'
import { useSpring } from '@react-spring/core'
import { a } from '@react-spring/three'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Label.glb')
  const [expand, setExpand] = useState(false);
  const radius = window.innerHeight / 150
  const y = radius * Math.sin(2 * Math.PI * (3 / 3))
  const x = radius * Math.cos(2 * Math.PI * (3 / 3))
  const s = 0.5
  const scaleUp = s * window.innerWidth / 2000
  const scaleDown = s * window.innerWidth / 2000

  const animatedProps = useSpring({
    hovered: expand ? [0.6, 0.6, 0.6] : [0.5, 0.5, 0.5],
  });

  return (
    <a.group 
      ref={group} 
      {...props} 
      dispose={null}
      rotation={[Math.PI / -0.01, -1.5, 3]}
      onPointerUp={() => window.appHistory.push("/connect")}
      // position={[-4, -0.5, 2]}
      position={[`${x}`, -0.5, `${y}`]}
      scale={animatedProps.hovered}
      onPointerOver={() => setExpand(true)}
      onPointerOut={() => setExpand(false)}
      >
      <group position={[0, 0, -0.29]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[1.39, -0.05, 0.37]}>
              <mesh material={materials.Lable_V3} geometry={nodes.Lable_V3_Lable_02_001.geometry} />
            </group>
            <group position={[1.39, 0.02, -3.04]}>
              <mesh material={materials.Metal} geometry={nodes.Lable_V3_Metal_01_001.geometry} />
            </group>
            <group position={[1.39, 0.02, -3.13]}>
              <mesh material={materials.Lable_V3} geometry={nodes.Lable_V3_Metal_02_001.geometry} />
            </group>
          </group>
        </group>
      <Html scaleFactor={5} position={[0.1, 5.2, -0.2]}>
        <h1 className="threeD__label">Connect</h1>
      </Html>
    </a.group>
  )
}

useGLTF.preload('/Label.glb')
