/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

import { Html } from 'drei';

import { useSpring } from '@react-spring/core';
import { a } from '@react-spring/three';

export default function Model(props) {

  const [expand, setExpand] = useState(false);
  // React spring expand animation

  const animatedProps = useSpring({
    hovered: expand ? [9, 9, 9] : [6, 6, 6],
  });

  function handlePageRouting() {
    window.appHistory.push("/gallery");
  };

  const group = useRef()
  const { nodes, materials } = useGLTF('/logoButton.glb')
  return (
    <a.group ref={group} {...props} dispose={null}
      position={[-4, -0.5, 2]}
      rotation={[1.67, 0.2, 0.7]}
      scale={animatedProps.hovered}
      onPointerOver={() => setExpand(true)}
      onPointerOut={() => setExpand(false)}
    >
      <mesh
        material={materials['Material.001']}
        geometry={nodes.Curve.geometry}
        position={[0.01, 0.01, -0.01]}
        scale={[4.18, 3.84, 4.18]}
      />
      <mesh
        material={materials.SVGMat}
        geometry={nodes.Curve001.geometry}
        position={[0, -0.01, 0.01]}
        scale={[4.18, 4.96, 4.18]}
      />
      <mesh
        material={materials.Material}
        geometry={nodes.Curve002.geometry}
        position={[0, -0.03, 0.02]}
        scale={[4.18, 6.56, 4.18]}
      />
      <Html scaleFactor={5} position={[-0.1, -0.02, 0.3]}>
        <h1 style={{ color: 'white', opacity: '0.2' }}>About</h1>
      </Html>
    </a.group>
  )
}

useGLTF.preload('/logoButton.glb')
