/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

import { Html } from 'drei';

import { useSpring } from '@react-spring/core';
import { a } from '@react-spring/three';

export default function Shirt(props) {
  const [expand, setExpand] = useState(false);
  const radius = window.innerHeight / 150
  const y = radius * Math.sin(2 * Math.PI * (2 / 3))
  const x = radius * Math.cos(2 * Math.PI * (2 / 3))
  const s = 0.06
  const scaleUp = s * window.innerWidth / 2000
  const scaleDown = s * window.innerWidth / 2000

  const animatedProps = useSpring({
    hovered: expand ? [0.08, 0.08, 0.08] : [0.07, 0.07, 0.07],
  });

  // const animatedProps = useSpring({
  //   hovered: expand ? [0.05, 0.05, 0.05] : [0.04, 0.04, 0.04],
  // });

  const group = useRef()
  const { nodes, materials } = useGLTF('/Shirt1.glb')

  return (
    <a.group 
      ref={group} 
      {...props} 
      dispose={null}
      onPointerOver={() => setExpand(true)}
      onPointerOut={() => setExpand(false)}
      scale={animatedProps.hovered}
      // position={[0, -2, -4.5]}
      position={[`${x}`, -2.3, `${y}`]}
      rotation={[Math.PI / 2, 0, 2.5]}
    >
      <mesh 
        onPointerUp={() => window.appHistory.push("/shop")}
        material={materials.wire_177148027} 
        geometry={nodes.T_Shirt_V2.geometry} 
      />
        <Html scaleFactor={5} position={[0, -2.5, 5.5]} >
          <h1 className="threeD__label">Shop</h1>
        </Html>
    </a.group>
  )
}

useGLTF.preload('/Shirt1.glb')
