/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, useState, useEffect } from 'react'
import { useGLTF, Html } from '@react-three/drei'
import { useSpring } from '@react-spring/core';
import { a } from '@react-spring/three';

export default function Shirt({props}) {

  useEffect(() => {
    const radius = document.documentElement.clientWidth / 150
  
    if (radius <= 6 ) {
      return setMaxRadius(radius)
    } 
  
    if (radius >= 6 ) {
      return setMaxRadius(6)
    }
  },[])

  const [expand, setExpand] = useState(false);
  const [maxRadius, setMaxRadius] = useState()
  const radius = window.innerWidth / 150
  const y = maxRadius * Math.sin(2 * Math.PI * (2 / 3))
  const x = maxRadius * Math.cos(2 * Math.PI * (2 / 3))

  const animatedProps = useSpring({
    hovered: expand ? [0.06, 0.06, 0.06] : [0.05, 0.05, 0.05],
  });

  const group = useRef()
  const { nodes, materials } = useGLTF('/Shirt1.glb')

  return (
    <a.group 
      ref={group} 
      {...props}
      dispose={null}
      onPointerOver={e => { setExpand(true)  }}
      onPointerOut={e => {setExpand(false)  }}
      scale={animatedProps.hovered}
      position={[`${x}`, -2.3, `${y}`]}
      rotation={[Math.PI / 2, 0, 2.5]}
    >
      <mesh 
        onPointerUp={() => window.appHistory.push("/shop")}
        material={materials.wire_177148027} 
        geometry={nodes.T_Shirt_V2.geometry} 
      />
        <Html scaleFactor={5} position={[0, -2.5, 5.5]} zIndexRange={[1, 0]}>
          <h1 className="threeD__label">Shop</h1>
        </Html>
    </a.group>
  )
}

useGLTF.preload('/Shirt1.glb')
